name: Generate CSR and Upload Certificate to SCC

on:
  workflow_dispatch:
    inputs:
      certificate_type:
        description: 'Type of certificate to generate (e.g., system or ca or ui)'
        required: true
        type: choice
        options:
          - system
          - ca
          - ui


env:
  PATH_TO_TFSCRIPT: 'Flow2'
  TEMP_PLAN_OUTPUT : 'plan-output.tfplan'

permissions:
  contents: read

jobs:
  test:
    name: Generate CSR and Upload Certificate to SCC
    runs-on: ubuntu-latest

    env:
      SCC_USERNAME: ${{ secrets.SCC_USERNAME }}
      SCC_PASSWORD: ${{ secrets.SCC_PASSWORD }}
      SCC_INSTANCE_URL: ${{ secrets.SCC_INSTANCE_URL }}

      CERTIFICATE_TYPE: ${{ github.event.inputs.certificate_type }}

    steps:
      - name: Check out Git repository
        id: checkout_repo
        uses: actions/checkout@v6

      - name: Setup Terraform
        id: setup_terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: Show Selected Inputs
        run: |
          echo "Certificate Type: $CERTIFICATE_TYPE"

      - name: Generate Terraform main.tf dynamically
        shell: bash
        run: |
          cat <<EOF > ${{ env.PATH_TO_TFSCRIPT }}/main.tf

          action "scc_generate_csr" "${CERTIFICATE_TYPE}_cert" {
            config {
              type     = "${CERTIFICATE_TYPE}"
              key_size = 2048

              subject_dn = {
                cn    = "cloud-connector.example.com"
                o     = "SAP"
                ou    = "BTP Engineering and Delivery Services India"
                l     = "Bangalore"
                st    = "Karnataka"
                c     = "IN"
                email = "admin@example.com"
              }

              subject_alternative_names = [
                {
                  type  = "DNS"
                  value = "cloud-connector.example.com"
                },
                {
                  type  = "DNS"
                  value = "cc.internal.local"
                }
              ]
            }
          }
          EOF

      - name: Terraform Init
        id: terraform_init
        shell: bash
        run: |
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT }} init -no-color

      - name: Terraform Plan - Generate CSR
        id: terraform_plan_generate_csr
        shell: bash
        run: |
          set +e

          terraform -chdir=${{ env.PATH_TO_TFSCRIPT }} plan \
            -invoke=action.scc_generate_csr.${{ env.CERTIFICATE_TYPE }}_cert \
            -out=${{ env.TEMP_PLAN_OUTPUT }} \
            -no-color \
            -detailed-exitcode

          EXIT_CODE=$?

          echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT

          if [ $EXIT_CODE -eq 1 ]; then
            echo "Error during terraform plan execution"
            exit 1
          elif [ $EXIT_CODE -eq 2 ]; then
            echo "Changes detected in terraform plan"
          else
            echo "No changes detected in terraform plan"
          fi

      - name: Terraform Apply - Generate CSR
        if: steps.terraform_plan_generate_csr.outputs.exitcode == '0' || steps.terraform_plan_generate_csr.outputs.exitcode == '2'
        id: terraform_apply_generate_csr
        shell: bash
        run: |
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT }} apply \
            -auto-approve \
            -no-color \
            ${{ env.TEMP_PLAN_OUTPUT }}

      - name: Verify CSR file exists
        shell: bash
        run: |
          ls -lah
          test -f "${{ env.PATH_TO_TFSCRIPT }}/${{ env.CERTIFICATE_TYPE }}_csr.pem"

      - name: Setup OpenSSL
        shell: bash
        run: |
          openssl version

      - name: Generate CA Certificate and Key
        shell: bash
        run: |
          cd ${{ env.PATH_TO_TFSCRIPT }}

          openssl genrsa -out myCA.key 2048

          openssl req \
            -x509 \
            -new \
            -nodes \
            -key myCA.key \
            -sha256 \
            -days 3650 \
            -out myCA.pem \
            -subj "/C=IN/ST=Karnataka/L=Bangalore/O=SAP/OU=BTP Engineering and Delivery Services India/CN=Example-Root-CA"

      - name: Sign CSR using OpenSSL
        shell: bash
        run: |
          cd ${{ env.PATH_TO_TFSCRIPT }}

          openssl x509 \
            -req \
            -in ${{ env.CERTIFICATE_TYPE }}_csr.pem \
            -CA myCA.pem \
            -CAkey myCA.key \
            -CAcreateserial \
            -out ${{ env.CERTIFICATE_TYPE }}_cert.pem \
            -days 365 \
            -sha256

      - name: Create Signed Chain
        shell: bash
        run: |
          cd ${{ env.PATH_TO_TFSCRIPT }}

          cat ${{ env.CERTIFICATE_TYPE }}_cert.pem myCA.pem > signed_chain.pem

      - name: Append Signed Chain Resource
        shell: bash
        run: |
          cat <<'EOF' >> ${{ env.PATH_TO_TFSCRIPT }}/main.tf

          resource "scc_system_certificate_signed_chain" "uploaded_cert" {
            signed_chain = file("${path.module}/signed_chain.pem")
          }
          EOF

      - name: Terraform Plan - Upload Signed Chain
        id: terraform_plan_signed_chain
        shell: bash
        run: |
          set +e

          terraform -chdir=${{ env.PATH_TO_TFSCRIPT }} plan \
              -no-color \
            -detailed-exitcode \
            -out=${{ env.TEMP_PLAN_OUTPUT }}

          EXIT_CODE=$?

          echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT

          if [ $EXIT_CODE -eq 1 ]; then
            echo "Error during terraform plan execution"
            exit 1
          elif [ $EXIT_CODE -eq 2 ]; then
            echo "Changes detected in terraform plan"
          else
            echo "No changes detected in terraform plan"
          fi

      - name: Terraform Apply - Upload Certificate
        if: steps.terraform_plan_signed_chain.outputs.exitcode == '0' || steps.terraform_plan_signed_chain.outputs.exitcode == '2'
        id: terraform_apply_signed_chain
        shell: bash
        run: |
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT }} apply \
            -auto-approve \
            -no-color \
            ${{ env.TEMP_PLAN_OUTPUT }}
